export const AUTH_START = 'AUTH_START';
export const AUTH_SUCCESS = 'AUTH_SUCCESS';
export const AUTH_FAIL = 'AUTH_FAIL';
export const USER_LOGOUT ='USER_LOGOUT';

export const FORM_SUBMIT_START = 'FORM_SUBMIT_START';
export const FORM_SUBMIT_SUCCESS = 'FORM_SUBMIT_SUCCESS';
export const FORM_SUBMIT_FAILED = 'FORM_SUBMIT_FAILED';

export const INPUT_VALUE_CHANGED = 'INPUT_VALUE_CHANGED';
export const RESET_CLICKED = 'RESET_CLICKED';

export const ADD_CLICKED = 'ADD_CLICKED';
export const TABLE_DELETE_ROW = 'TABLE_DELETE_ROW';

export const FORM_VALID_CHECK = 'FORM_VALID_CHECK';
export const CLEAR_ALL_INPUT = 'CLEAR_ALL_INPUT';